### ISSUE TITLE
GitHub main branch merge rule 추가

### ISSUE THREAD

**Issue by kchung1995** [fingersdanny/MyPlace#5]
GitHub에서 설정할 수 있는 branch protection rule 중에서, pr을 통해서만, n개 이상의 approve가 있을 때만 merge할 수 있도록 규칙을 만들 수 있습니다. [이 글](https://kth990303.tistory.com/317)을 참고하면 좋습니다.
해당 규칙을 설정해서, pr 없는 main branch merge를 막아 주세요.

**Comment by fingersdanny** [comment]
- main branch protection rule 확인했습니다. pr을 통해서만 하도록 되어 있었는데 어제 project 올릴때 local의 main branch에서 commit하고 올렸더니 내역이 이상해졌네요 다시 돌려 놓고 처음부터 pr하겠습니다.
![main_branch_merge_rule](https://github.com/fingersdanny/MyPlace/assets/54776553/68e5a77c-2d2e-47e0-9038-5465de8a8847)
